# Generated by Django 5.2.6 on 2026-08-31 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('name', models.CharField(choices=[('A1', 'Batch A1'), ('A2', 'Batch A2'), ('B1', 'Batch B1'), ('B2', 'Batch B2'), ('C', 'Batch C')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year', 'name'],
                'constraints': [models.UniqueConstraint(fields=('year', 'name'), name='unique_batch_per_year')],
            },
        ),
    ]
