# Generated by Django 5.2.6 on 2026-08-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.CharField(choices=[('zip', 'Zip'), ('typing', 'Typing')], max_length=20),
        ),
    ]
