# Generated by Django 5.2.6 on 2026-07-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
