# Generated by Django 5.2.6 on 2026-07-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_batch_code_no',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='batch',
            field=models.CharField(choices=[('A1', 'Batch A1'), ('A2', 'Batch A2'), ('B1', 'Batch B1'), ('B2', 'Batch B2'), ('C', 'Batch C')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='code_no',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('batch', 'code_no')},
        ),
    ]
