# Generated by Django 5.2.6 on 2026-08-31 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('users', '0002_remove_customuser_unique_batch_code_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='batch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.batch'),
        ),
    ]
